### ISSUE TITLE
Crash: Ktor + Kotlin Serdes

### ISSUE THREAD

**Issue by vinchamp77** [vinchamp77/Demo_SimpleRestAPI#1]
```
2022-08-29 18:05:53.390 21233-21233/vtsen.hashnode.dev.simplerestapidemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: vtsen.hashnode.dev.simplerestapidemo, PID: 21233
    io.ktor.network.sockets.ConnectTimeoutException: Connect timeout has expired [url=https://www.themealdb.com/api/json/v1/1/categories.php, connect_timeout=unknown ms]
        at io.ktor.client.features.HttpTimeoutKt.ConnectTimeoutException(HttpTimeout.kt:183)
        at io.ktor.client.features.HttpTimeoutKt.ConnectTimeoutException$default(HttpTimeout.kt:180)
        at io.ktor.client.engine.cio.Endpoint.getTimeoutException(Endpoint.kt:235)
        at io.ktor.client.engine.cio.Endpoint.connect(Endpoint.kt:227)
        at io.ktor.client.engine.cio.Endpoint.access$connect(Endpoint.kt:21)
        at io.ktor.client.engine.cio.Endpoint$connect$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by vinchamp77** [comment]
Not reproducible, maybe I fixed it.
